### ISSUE TITLE
Admin say, yell, kick, ban and other

### ISSUE THREAD

**Issue by IamDontNoob** [Prophet731/BFAdminCP#93] opened 2015-07-10 18:16 UTC
Hello.
Today I'm update BFAdminC to ver.2.0.0
And now see i'm can't kick, ban players from site, and can'n Say messages in chat and admin Yell.
So conceived, or it was a mistake?

**Comment by IamDontNoob** [comment] 2015-07-10 18:39
And when i'm press to "Profile" or account i'm see eror 404 This page not found

**Comment by Prophet731** [comment] 2015-07-11 08:19
Some things are missing from v2.0.0 as I wrote in the post on our site. The admin actions on the live scoreboard are not implemented yet but will be in the next release which im still working on. This includes the profile as well. I'll have the next release ready sometime this month and that will be the finished version.

**Comment by IamDontNoob** [comment] 2015-07-31 16:52
Hello.
Month end) when new version with admin action release?

**Comment by Prophet731** [comment] 2015-07-31 23:47
Read my post here. I'm delaying it for a few days as I have IRL stuff to handle.

http://www.adkgamers.com/topic/117610-bfacp-version-200/page-7#entry421006

**Comment by IamDontNoob** [comment] 2015-08-01 14:17
Hello okay.
But adkgamers.com not opened in RU :) http://i.imgur.com/vovPMoe.png

**Comment by Subman-CNP** [comment] 2015-08-01 20:37
I've the same problem here in Poland (my ISP is Orange). adkgamers.com is not available here. It was available about 10 days ago however now the www.adkgamers.com (158.69.35.255) is not avaialbe. I can't it even ping, Here's what I'm get when I'm trying to traceroute to your web site: http://i.imgur.com/R8GOOJd.png

**Comment by Prophet731** [comment] 2015-08-02 01:11
I'll see if any protection got put up that might be the cause of it.

**Closed** 2015-08-09 04:08 UTC
Labels: Question
