### ISSUE TITLE
Issue: Map stats date arrange issue

### ISSUE THREAD

**Issue by iraqiboy90** [Prophet731/BFAdminCP#59] opened 2015-02-11 22:14 UTC
http://imageshack.com/a/img538/2964/HoTXdO.png

When rearranging pr date, suddenly the last day cannot be on top.
Today is 11th, and it cant be on top. doesnt matter how many times I re-arrange it

ID sorting is ok,
Load, round start, round end sorting is not ok

**Comment by Prophet731** [comment] 2015-02-12 07:48
This is an issue with datatables and the way I generated the datetime in the view. This is being rewritten to actually work with dates.

**Comment by ColColonCleaner** [comment] 2015-02-12 21:56
Enhancement/logic change? This is a bug, lol.

**Comment by Prophet731** [comment] 2015-02-12 22:20
Its not a bug. It just the way datatables works and the date I echo out isn't the right format. So logic change, yea.

**Comment by ColColonCleaner** [comment] 2015-02-12 22:23
Logic change is in regard to how it should work, like a documented definition. "We said it will work like that, but now we say it will work like this instead", that's a logic change. If it doesn't operate as intended it's a bug.

**Comment by Prophet731** [comment] 2015-02-12 22:50
There. Happy?

**Comment by ColColonCleaner** [comment] 2015-02-12 23:00
I'll settle for it :)

**Comment by Prophet731** [comment] 2015-04-05 06:26
This is resolved by using moment and angular ng-tables.

**Closed by Prophet731** 2015-04-05 06:26 UTC
Labels: Bug, Enhancement, Logic Change
