### ISSUE TITLE
Issue: Issue on leaderboard

### ISSUE THREAD

**Issue by iraqiboy90** [Prophet731/BFAdminCP#55] opened 2015-02-09 01:25 UTC
Hello

I wanted to add a new server today, then I was forced to upgrade from the 1.5 beta to the 2.0 rc1.
I applied these:
https://github.com/Prophet731/BFAdminCP/blob/master/app/storage/sql/upgrades/1.5.0beta1_2.0.0RC1.sql
https://gist.github.com/Prophet731/4e0250c82cb2082667f6

Issue 1:
When Livescoreboard -> selecting new server
Only chatbox shows up and the following error box shows up periodically:
end() expects parameter 1 to be array, string given

Issue 2:
On the homepage, I dont see the servers anymore.
http://img661.imageshack.us/img661/3776/RN7o3v.png

**Comment by iraqiboy90** [comment] 2015-02-09 08:55
Note: I already tried re-adding the rcon password

**Comment by Prophet731** [comment] 2015-02-09 20:36
This was caused by missing maps and gamemodes. Fixed in cadf5e3cb0e9ef80f9f86a61145692a3a1f54257

**Closed by Prophet731** 2015-02-09 20:36 UTC
Labels: Enhancement
